[package]
name = "try_image"
version = "0.1.0"
edition = "2021"

[features]
default = ["sixel"]
sixel = ["sixel-rs"]

[dependencies]
image = "0.24"
sixel-rs = { version = "0.5.0", optional = true }
tempfile = "3.8"
terminal_size = "0.3"
ctrlc = "3.4"